name: RVBBERDUCK
favicon: null
layout_spectrum: 0.38182923034764826
typography_spectrum: 0.2453939043916762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.15165874571539462
  lightness: 0.29869739268906415
  saturation: 0.019207268254831433
  rhythmicContrast: 0.8436912118922919
purpose: []
